```{r}
library(tidyverse)
d <- read_csv("data/raw/oregan-etal-2013/meso.csv")
species_letters <- tibble(species = c("spadefoot", "treefrog", "redlegged"),
  sp = c("b", "c", "a"))
d <- inner_join(d, species_letters) %>%
  rename(species_true = species, species = sp) %>%
  mutate(warming = ifelse(climate == "warming", 1, 0),
    drying = ifelse(drying == "temp", 1, 0)) %>%
  select(tank, date, drying, warming, species, species_true, svl, mass, time) %>%
  mutate(species = as.factor(species), tank = as.factor(tank)) %>%
  select(-time, -date)
d
```

```{r}
d <- mutate(d,
  sp_a = ifelse(species == "a", 1, 0),
  sp_b = ifelse(species == "b", 1, 0),
  sp_c = ifelse(species == "c", 1, 0),
  sp_a_cent = sp_a - mean(sp_a),
  sp_b_cent = sp_b - mean(sp_b),
  sp_c_cent = sp_c - mean(sp_c),
  warming_cent = warming - mean(warming))
select(d, -drying, -mass, -species_true)
d <- filter(d, species != "c")

# implicit comparison to species a
(m <- lmer(svl ~ (warming + species)^2 + (1 | tank), data = d))
(m <- lmer(svl ~ warming * species + (1 | tank), data = d))
(m <- lmer(svl ~ warming * sp_b + warming * sp_c + (1 | tank), data = d))

# intercept removed
(m <- lmer(svl ~ 0 + warming * species + (1 | tank), data = d))
(m <- lmer(svl ~ 0 + sp_a + warming * sp_b + warming * sp_c + 
    (1 | tank), data = d))

# centered
(m <- lmer(svl ~ 0 + warming_cent * sp_b_cent + warming_cent * sp_c_cent + 
    (1 | tank), data = d))

(m <- lmer(svl ~ warming + species + (1 | tank), data = d))

(m1 <- lmer(svl ~ warming * species + (1 | tank), data = d))
fixef(m1)[[1]] + fixef(m1)[[3]]

(m2 <- lmer(svl ~ warming_cent * sp_b_cent + (1 | tank), data = d))

x <- max(d$sp_b_cent)
x <- max(d$sp_b_cent)
fixef(m2)[[1]] + x * fixef(m2)[[3]]
fixef(m2)[[1]] + (x - 1) * fixef(m2)[[3]]

17.9294 + 0.8529063 * 1.0893 
17.9294 + 0.8529063 * 1.0893 
```



```{r}
library(lme4)
m <- lmer(svl ~ (warming + drying + species)^2 + (1 | tank), data = d)

# m2 <- lmer(log(svl) ~ (warming + drying + sp)^2 + ((warming + drying + sp)^2 | tank), data = d)

# m3 <- glmmTMB::glmmTMB(log(svl) ~ (warming + drying + species)^2 + ((warming + drying + species)^2 | tank), data = d)
# summary(m3)

```

```{r}
plot(m)
plot(m, resid(., type = "pearson") ~ fitted(.) | drying + warming, abline = 0)
summary(m)

d$svl_res <- residuals(m, type = "pearson")
ggplot(d, aes(as.factor(tank), svl_res, colour = paste(drying, warming))) +
  geom_boxplot() + 
  geom_hline(yintercept = 0) + 
  xlab("") + ylab("SVL residuals (mm)")

fe <- fixef(m)
se <- arm::se.fixef(m)

arm::display(m)

fe_comp <- fe[["drying:speciesb"]] + fe[["drying"]]
se_comp <- sqrt(se[["drying:speciesb"]]^2 - se[["drying"]]^2)
fe_comp + c(-1.96, 1.96) * se_comp

comparison_effect <- function(model, base_par, comparison_par) {
  if (class(model) == "glmmTMB") {
    fe <- fixef(model)$cond
    se <- coef(summary(m4))$cond[,"Std. Error"]
  } else {
    se <- arm::se.fixef(model)
    fe <- fixef(model)
  }
  if (base_par != comparison_par) {
    fe_comp <- fe[[comparison_par]] + fe[[base_par]]
    se_comp <- sqrt(se[[comparison_par]]^2 - se[[base_par]]^2)
  } else {
    fe_comp <- fe[[base_par]]
    se_comp <- se[[base_par]]
  }
  
  ci <- fe_comp + c(-1.96, 1.96) * se_comp
  data.frame(lwr = ci[1], est = fe_comp, upr = ci[2])
}

comparison_effect(m, "drying", "drying")
comparison_effect(m, "drying", "drying:speciesb")
comparison_effect(m, "drying", "drying:speciesc")

base_par <- rep("drying", 3)
comparison_par <- c("drying", "drying:speciesb", "drying:speciesc")
out <- purrr::map2_df(base_par, comparison_par, comparison_effect, model = m)
out
```

